name: food_delivery_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  get: ^4.6.5
  get_storage: ^2.0.3
  cached_network_image: ^3.2.1
  shimmer: ^2.0.0

  firebase_core: ^2.4.0
  firebase_messaging: ^14.1.4
  firebase_storage: ^11.0.7
  firebase_auth: ^4.2.0
  cloud_firestore: ^4.0.0

  url_launcher: ^6.1.7
  carousel_slider: ^4.1.1
  image_picker: ^0.8.6

  geocoding: ^2.1.0
  geolocator: ^9.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.11.0"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21

  
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf

